# Generated by Django 4.1.1 on 2022-12-09 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=90)),
                ('description', models.FloatField()),
                ('discount', models.FloatField()),
            ],
        ),
    ]
